workTodo
HardNikolai/WorkNick pull request #11
Opened 2022-10-28 11:00 UTC by HardNikolai

2022-10-31 05:24 UTC, DanilVezmenov requested changes

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
Почему ветка называется WORKTODO это же учет расходов?

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
![image](https://user-images.githubusercontent.com/107387472/198934104-33662840-bd90-4e18-842a-fcdf65a765e3.png)
мне кажется что-то не так  с введенной суммой

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
![image](https://user-images.githubusercontent.com/107387472/198934185-e1ae85d2-7212-42af-ad40-e7f67c69639e.png)
Предлагаю стилизовать приложение и сделать его более привлекательным, текст плейсхолдеров дублируется и все выглядит слипшимся, можно добавить больше дизайнерского видения :)

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
![image](https://user-images.githubusercontent.com/107387472/198934306-5a0fd815-6838-4d5f-a404-2e0c6a6222a5.png)
 разве я мог потратить деньги в 2026 году?

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
![image](https://user-images.githubusercontent.com/107387472/198934371-fbbdccee-dcfa-4a39-a079-a60191c2db82.png)
аналогично, нужна валидация даты и на стороне клиента и на стороне сервера

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
![image](https://user-images.githubusercontent.com/107387472/198934447-314b147c-38e4-44fc-ab81-614c50312c2b.png)
![image](https://user-images.githubusercontent.com/107387472/198934454-b7bf5731-7380-4f5d-a76e-379f3d25992a.png)

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
Сделай это не через alert это не должно быть блокирующим событием, и в конце концов после двух алертов у меня записался -1 рубль на клиенте

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
![image](https://user-images.githubusercontent.com/107387472/198934622-ead69176-aa1c-4e28-83d2-9507e626dc54.png)
добавление  расходов с пустым текстом

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +<!DOCTYPE html>
![image](https://user-images.githubusercontent.com/107387472/198934976-21dc18ef-b868-4b4d-9f42-00f460b59ac5.png)
картинка 1 -> жму сохранить -> картинка 2 
![image](https://user-images.githubusercontent.com/107387472/198935053-26029e80-9ee9-4660-87ae-8ec768db9bdc.png)
Мы либо сохраняем все, либо не открываем несколько редакторов

2022-10-31 05:24 UTC, DanilVezmenov commented on 7.index.html
> +                <button class="add-a-list" onclick="onClickButton()">Добавить</button>
onClickButton

2022-10-31 05:24 UTC, DanilVezmenov commented on NODEJS/package.json
> +{
зачем ты заливаешь node_modules ?
<img width="298" alt="image" src="https://user-images.githubusercontent.com/107387472/198935223-034335cc-5a15-4be2-baa3-e1f97299e70c.png">
это должно быть в ignore

2022-10-31 05:24 UTC, DanilVezmenov commented on NODEJS/app.js
> +require('dotenv').config();
порядок

2022-10-31 05:24 UTC, DanilVezmenov commented on NODEJS/src/modules/controllers/task.controller.js
> +            }
как это должно работать ?
dayReq == 'Invalid Date'

Сделай деструктуризацию

2022-10-31 05:24 UTC, DanilVezmenov commented on NODEJS/src/modules/controllers/task.controller.js
> +                date: dayReq
у тебя есть  некоторая трата у нее есть 

название  name
кол-во потраченных денег value или cost 
и дата (тут у тебя все окей)

2022-10-31 05:24 UTC, DanilVezmenov commented on NODEJS/src/modules/controllers/task.controller.js
> +                date: dayReq
Выбирай названия переменных внимательнее, и вообще почему они через snake case

2022-10-31 05:24 UTC, DanilVezmenov commented on NODEJS/src/modules/controllers/task.controller.js
> +        if (checkTypePrice) {
надо подумать зачем тут это и переделать

2022-10-31 05:24 UTC, DanilVezmenov commented on creation.js
> +    const checkValueSecond = valueInputSecond.trim();
непонятный нейминг переменных

Зачем нам trim для поля где невозможно поставить пробел?

2022-10-31 05:24 UTC, DanilVezmenov commented on creation.js
> +                let result = await resp_all.json();
разделить функционал на отдельные запросы

2022-10-31 05:24 UTC, DanilVezmenov commented on creation.js
> +        input_expenses.value = '';
вынести в отдельную функцию

2022-10-31 05:24 UTC, DanilVezmenov commented on creation.js
> +    }
переделать, ты можешь через innerHTML  сделать это в одну строку.

2022-10-31 05:24 UTC, DanilVezmenov commented on creation.js
> +        getBlockSum.innerText = `Итого: ${allSum}р.`;
я бы предложил считать сумму в отдельной функции и внутри рендер вызывать ее только для того чтобы записать готовое значение

2022-10-31 05:24 UTC, DanilVezmenov commented on creation.js
> +            render();
исполняется вне зависимости  от bulTextPlace && bulTextDate && bulTextExpenses, значит должно быть вынесено за пределы if else

2022-10-31 05:39 UTC, DanilVezmenov requested changes

2022-10-31 05:39 UTC, DanilVezmenov commented on NODEJS/src/modules/controllers/task.controller.js
> +        if (delete_task.deletedCount === 1) {
описывал это в todo list

2022-10-31 05:39 UTC, DanilVezmenov commented on creation.js
> +const options = {day: 'numeric', month: 'numeric', year: 'numeric'};
не могу понять что это

2022-10-31 08:07 UTC, Paul-Petrash requested changes

2022-10-31 08:07 UTC, Paul-Petrash commented on NODEJS/src/modules/controllers/task.controller.js
> +            if (dayReq == 'Invalid Date') {
Лучше идти от противного если нет даты то сразу возращать ошибку и не плодить уровни вложенности

2022-10-31 08:07 UTC, Paul-Petrash commented on creation.js
> +            const resp_all = await requestProcessing('http://localhost:8000/tasks', 'GET');
Зачем делать повторный запрос на получение всего списка ?

2022-11-13 22:35 UTC, DanilVezmenov approved these changes

2022-11-13 22:35 UTC, merged